### ISSUE TITLE
[Bug] Short description.

### ISSUE THREAD

**Issue by otajalol00** [WellCodeIsDelicious/WSA-Script#2]
### Steps to reproduce

1. 
2. 
3. 
a

### Expected behaviour

a

### Actual behaviour

a

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal

latest

### Linux distribution info/Linux

ubuntu

### Windows version/Windows

11

### Build Parameters

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico  --root-sol magisk
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement

- [X] I am using latest commit of MagiskOnWSALocal commit

### Logs

<details>

```
# Replace this line with the log
```
</details>

**Comment by YT-Advanced** [comment]
Hmm, Use from the main repos (my repo) instead:
https://github.com/YT-Advanced/WSA-Script/
